### ISSUE TITLE
after the last update with git pull

### ISSUE THREAD

**Issue by lpadumorvan** [WWBN/AVideo#9369]
Hi

I have : 
Parse error: syntax error, unexpected '|', expecting '{' in /var/www/AVideo/vendor/thecodingmachine/safe/lib/special_cases.php on line 434

Thanks

DV

**Comment by DanielnetoDotCom** [comment]
What PHP version are you using?

I guess you need to udpate it to version 8 or higher

**Comment by lpadumorvan** [comment]
php 7.4.3

idem this : https://github.com/MISP/MISP/issues/9204 ?
resolve idem => php 8.0 ?
Thanks
DV

**Comment by DanielnetoDotCom** [comment]
yes PHP 8+ may resolve it

**Comment by lpadumorvan** [comment]
php7.4.3 update to 8.3: problem solved !
Thanks
DV

**Comment by millzee01** [comment]
Hi Daniel, after upgrading to 8.3.15 im still seeing:

Parse error: syntax error, unexpected '|', expecting '{' in /var/www/html/vendor/thecodingmachine/safe/lib/special_cases.php on line 434

since latest git update

only thing logged in the videos.log is:
[08-Jan-2025 11:10:01 America/Whitehorse] AVideoLog::DEBUG:      is_port_open(2053, 127.0.0.1) error Connection refused SCRIPT_NAME: /var/www/html/plugin/Scheduler/run.php
[08-Jan-2025 11:10:01 America/Whitehorse] AVideoLog::DEBUG:      WatchDog: socket port is not opened [2053] SCRIPT_NAME: /var/www/html/plugin/Scheduler/run.php
[08-Jan-2025 11:10:02 America/Whitehorse] AVideoLog::ERROR:      Socket server For better performance install PDO SQLite in your PHP SCRIPT_NAME: /var/www/html/plugin/YPTSocket/server.php
[08-Jan-2025 11:10:02 America/Whitehorse] AVideoLog::DEBUG:      Starting Socket server at port 2053 SCRIPT_NAME: /var/www/html/plugin/YPTSocket/server.php
[08-Jan-2025 11:10:02 America/Whitehorse] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Socket\Message::__construct(), 0 passed in /var/www/html/plugin/YPTSocket/server.php on line 254 and exactly 1 expected in /var/www/html/plugin/YPTSocket/Message.php:23
Stack trace:
#0 /var/www/html/plugin/YPTSocket/server.php(254): Socket\Message->__construct()
#1 {main}
  thrown in /var/www/html/plugin/YPTSocket/Message.php on line 23


whats strange is port 2053 is open both ways and was working before php and avideo update.

anything else i need to check?

**Comment by DanielnetoDotCom** [comment]
what php version are you using?

**Comment by DanielnetoDotCom** [comment]
Sorry I just see 8.3

Make sure you run this
`
sudo apt-get install php8.3-sqlite3
`

**Comment by millzee01** [comment]
Hi, 

i'll try this today thanks!
